# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jags
email: jags1285@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  I a Software Engineer with 10+ years of experience in developing web applications using Java, Spring Boot, Angular, React, Node.js, and other technologies. I am passionate about learning new technologies and sharing my knowledge with others. I am a self-taught developer and I believe that anyone can learn to code if they have the right resources and guidance. 
  
twitter_username: jagadeeshposni
github_username: jagadeeshposni
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "jagadeesh posni"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "design, develop, deploy, but first coffee! కృషి తో నాస్తి దుర్భిక్షం "
  links:
    - label: "london, UK"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://"  
    - label: "jags1285@hotmail.com"
      icon: "fas fa-fw fa-envelope"
      url: mailto:jags1285@hotmail.com
    - label: "twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/jagadeeshposni"
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jagadeeshposni"
    - label: "instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/nerd__next__door/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/jagadeeshposni"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jagadeeshposni"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/nerd__next__door/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
