title: "jagadeesh.co.uk"
name: "jagadeesh.co.uk"
email: jagadeeshposni@gmail.com
url: "https://jagadeesh.co.uk"
repository: "jagadeeshposni/jagadeeshposni.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Jagadeesh Posni"
  avatar : "/assets/images/headshot.jpg"
  bio    : "Thoughts on life, computing, photography and a bit of everything else. Keeping it simple."
  

  location: "London, UK"
  github : jagadeeshposni
  linkedin: jagadeesh-posni-25025246
  email  : jagadeeshposni@gmail.com

# # comments by disqus
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "jags-com"

# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: false
      toc_label: "Contents"
      read_time: false
      comments: false
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
