title: "jags"
name: "jags"
email: jagadeeshposni@gmail.com
url: "http://jagadeeshposni.github.io"
repository: "jagadeeshposni/jagadeeshposni.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Jagadeesh Posni"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I have started this blog to document some of my thoughts life, computing, photography. As it turns out writing requires a deep clarity of thought and perseverant effort. For now, I focus on improving the consistency factor."
  

  location: "London, UK"
  github : jagadeeshposni
  linkedin: jagadeesh-posni-25025246
  email  : jagadeeshposni@gmail.com

# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "jags-com"

# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: false
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
